### ISSUE TITLE
Duplication of recent commands

### ISSUE THREAD

**Issue by creold** [joshbduncan/AiCommandPalette#23]
@joshbduncan, calling Recent Commands from Recent Commands looks fun =) But it's better to make an exception so it doesn't add itself to the list =)
![2023-11-20 11 51 01](https://github.com/joshbduncan/AiCommandPalette/assets/32217031/d4528107-221a-472a-a89f-1d2ae39a026d)

**Comment by joshbduncan** [comment]
Ha, that's some inception type stuff... There is actually a condition in the code to keep that from happening but when I changed the type of the command to make it show up on the start screen the condition is no longer true. I think I may go ahead and at least implement the base of the start-up screen builder and that will fix this issue. Thanks for the heads up!

**Comment by joshbduncan** [comment]
@creold, this is fixed in the latest push. Please note that the command "Recent Commands" is in your preferences file, so it will still show until it cycles through the list (which could take a while). You can just run the "Clear Recent Commands" command your preferences file will be updated correctly.
