### ISSUE TITLE
FR: Nested command / Use palette to send value to script

### ISSUE THREAD

**Issue by RasmusMalver** [joshbduncan/AiCommandPalette#27]
Hi Josh,

I am still loving this wonderful plugin, and I've been going mental, writing scripts for Illustrator. In that; I hit an obstacle, that may be solvable, using the command palette:

When scripting, I can prompt the user for `text input`, and `ok` / `cancel`, but I can't ask the user to choose from a list. Imagine if the palette could get a choice from the user, and send it to the script. 

Case: I want a command to copy the active color to the clipboard. But I want to prompt the user for `CMYK` / `RGB` / `HEX`. I want to choose my script from the palette, and have the palette ask me to choose from the list.

Is that difficult to make? I'm thinking it could be an option, when building a workflow.

**Comment by joshbduncan** [comment]
@RasmusMalver, that is a really neat idea 👍. Not sure how to easily share the selected item with the next script but I definitely plan to work on this and see what I can come up with. Thanks so much!

**Comment by joshbduncan** [comment]
@RasmusMalver, I've got a working concept... Basically, you can create a "custom picker" where you enter a list of options (separated by newlines), and a name, and you get a new command that will present a picker with your options. When an option is "picked" the environment variable "aic_picker_last" is set. You can then access that variable in another script using `$.getenv("aic_picker_last")`. So a custom picker could be used stand alone or inside of a workflow. I have a few more ideas and lots of small fixes and finishing touches but the base functionality is coded in the tagged branch.

**Comment by joshbduncan** [comment]
Added the ability to have multiple selections in your custom picker as well. I just need to cleanup the picker builder dialog and add some localize for alternate languages and then I should be able to merge this into the next release. Cheers!

**Comment by RasmusMalver** [comment]
> @RasmusMalver, I've got a working concept... Basically, you can create a "custom picker" where you enter a list of options (separated by newlines), and a name, and you get a new command that will present a picker with your options. When an option is "picked" the environment variable "aic_picker_last" is set. You can then access that variable in another script using `$.getenv("aic_picker_last")`. So a custom picker could be used stand alone or inside of a workflow. I have a few more ideas and lots of small fixes and finishing touches but the base functionality is coded in the tagged branch.

Sounds great! Can you expand a bit? Where do I create the custom picker?

By the way; the fuzzy matching works wonderfully! The command palette is the best tool since Illustrator itself. I don't know why they've spent time making things like `Image Tracing` and `Perspective Grid`, instead of this. It's also opened my eyes for the possibilites with scripting. I don't understand why Adobe doesn't provide better support and community sharing opportunities.

**Comment by joshbduncan** [comment]
@RasmusMalver, you'll need to down the script from the `custom-pickers` branch ([direct link](https://github.com/joshbduncan/AiCommandPalette/blob/98a46a607fe5fc338fc75577a94781ee1cf6ec74/AiCommandPalette.jsx)).

Then when you launch the palette, search for "picker". You'll see 'Build Picker..."

![CleanShot 2024-05-02 at 16 54 16@2x](https://github.com/joshbduncan/AiCommandPalette/assets/44387852/8d5cfec9-ecb6-4a63-8df3-f7b3a0901b62)

Please note, the dialog is ugly and will have directions added, but simply add your options (each on a new line), choose if the palette should allow multiple selections, then click OK.

![CleanShot 2024-05-02 at 17 01 59@2x](https://github.com/joshbduncan/AiCommandPalette/assets/44387852/0f177880-1971-4642-9085-aca8fdb1ff4f)

Then build a workflow that incorporates your new custom picker...

![CleanShot 2024-05-02 at 17 06 21@2x](https://github.com/joshbduncan/AiCommandPalette/assets/44387852/596054ec-e3bc-44c5-bfaf-e319724a2497)

As you'll notice, I added a script as the second step (which covers your use case). The script is simple, and just reads the environment variable the custom picker sets with your choice...

```javascript
// anotherScript.jsx
var colorSpace = eval($.getenv("aic_picker_last"));
alert("Picked Color Space\n" + colorSpace);
```

Then just run your workflow...

![CleanShot 2024-05-02 at 17 17 11](https://github.com/joshbduncan/AiCommandPalette/assets/44387852/3de78544-9bf6-4b28-91a2-ae063e6de286)

Something to note, since the environment variable is saved, if the user cancels the picker, I set that environment variable so you can check for that in your script...

![CleanShot 2024-05-02 at 17 17 35](https://github.com/joshbduncan/AiCommandPalette/assets/44387852/5bef54b9-5da1-4982-90a7-f6718dfc7b39)

Last thing to note, if you enable multi-selection with your picker, the selected values will be returned as an array. For this to work, you must read the environment with the `eval()` method.

I may also work out a way where you can create and edit the picker right inside the workflow builder...

Let me know if this makes sense?

And, I'm glad to hear the fuzzy matching is working for you! I plan to make an official release with that included soon. It was a great suggestion. Cheers!

**Comment by joshbduncan** [comment]
@RasmusMalver,the latest commit in the picker branch now allows creating/building custom pickers within the workflow builder. You can also edit a pick from within the workflow if you double-click a picker workflow step. I plan to add an edit button so this is easier to be aware of.
